# Leaf Global Config
config-version: 3.0

###########
#  ASYNC  #
###########
async:
  async-entity-tracker:
    enabled: true
    compat-mode: false
    max-threads: 0
    keepalive: 60
  # **Experimental feature, may cause data lost in some circumstances!**
  async-playerdata-save:
    enabled: true
  async-pathfinding:
    enabled: true
    max-threads: 0
    keepalive: 60
  async-mob-spawning:
    enabled: true
  async-locator:
    enabled: true
    threads: 0
    keepalive: 60

##########
#  PERF  #
##########
performance:
  use-virtual-thread-for-async-chat-executor: true
  use-virtual-thread-for-async-scheduler: true
  create-snapshot-on-retrieving-blockstate: true
  inactive-goal-selector-throttle: true
  throttle-hopper-when-full:
    enabled: true
    skip-ticks: 0
  skip-map-item-data-updates-if-map-does-not-have-craftmaprenderer: true
  skip-ai-for-non-aware-mob: true
  reduce-packets:
    reduce-entity-move-packets: true
  optimized-powered-rails: true
  optimize-minecart:
    enabled: true
    skip-tick-count: 30
  # This may cause the inconsistent order of future compose tasks.
  faster-structure-gen-future-sequencing: true
  # Requires a JVM that supports RandomGenerator and the LXM generators.
  # Some JREs don't support this and will cause a crash.
  faster-random-generator:
    enabled: true
    random-generator: Xoroshiro128PlusPlus
    enable-for-worldgen: true
    warn-for-slime-chunk: true
    use-legacy-random-for-slime-chunk: false
  entity-timeouts:
    ALLAY: -1
    AREA_EFFECT_CLOUD: -1
    ARMADILLO: -1
    ARMOR_STAND: -1
    ARROW: -1
    AXOLOTL: -1
    BAT: -1
    BEE: -1
    BLAZE: -1
    BOAT: -1
    BOGGED: -1
    BREEZE: -1
    BREEZE_WIND_CHARGE: 200
    CAMEL: -1
    CAT: -1
    CAVE_SPIDER: -1
    CHEST_BOAT: -1
    CHEST_MINECART: -1
    CHICKEN: -1
    COD: -1
    COMMAND_BLOCK_MINECART: -1
    COW: -1
    CREEPER: -1
    DOLPHIN: -1
    DONKEY: -1
    DRAGON_FIREBALL: 150
    DROWNED: -1
    EGG: 300
    ELDER_GUARDIAN: -1
    ENDER_DRAGON: -1
    ENDER_PEARL: -1
    ENDERMAN: -1
    ENDERMITE: -1
    EVOKER: -1
    EVOKER_FANGS: -1
    EXPERIENCE_BOTTLE: -1
    EXPERIENCE_ORB: -1
    EYE_OF_ENDER: -1
    FIREWORK_ROCKET: -1
    FOX: -1
    FROG: -1
    FURNACE_MINECART: -1
    GHAST: -1
    GIANT: -1
    GLOW_SQUID: -1
    GOAT: -1
    GUARDIAN: -1
    HOGLIN: -1
    HOPPER_MINECART: -1
    HORSE: -1
    HUSK: -1
    ILLUSIONER: -1
    IRON_GOLEM: -1
    ITEM: -1
    OMINOUS_ITEM_SPAWNER: -1
    FIREBALL: 600
    LIGHTNING_BOLT: -1
    LLAMA: -1
    LLAMA_SPIT: 150
    MAGMA_CUBE: -1
    MOOSHROOM: -1
    MULE: -1
    OCELOT: -1
    PANDA: -1
    PARROT: -1
    PHANTOM: -1
    PIG: -1
    PIGLIN: -1
    PIGLIN_BRUTE: -1
    PILLAGER: -1
    POLAR_BEAR: -1
    POTION: -1
    PUFFERFISH: -1
    RABBIT: -1
    RAVAGER: -1
    SALMON: -1
    SHEEP: -1
    SHULKER: -1
    SHULKER_BULLET: -1
    SILVERFISH: -1
    SKELETON: -1
    SKELETON_HORSE: -1
    SLIME: -1
    SMALL_FIREBALL: 400
    SNIFFER: -1
    SNOW_GOLEM: -1
    SNOWBALL: 200
    SPAWNER_MINECART: -1
    SPECTRAL_ARROW: -1
    SPIDER: -1
    SQUID: -1
    STRAY: -1
    STRIDER: -1
    TADPOLE: -1
    TNT_MINECART: -1
    TRADER_LLAMA: -1
    TRIDENT: -1
    TROPICAL_FISH: -1
    TURTLE: -1
    VEX: -1
    VILLAGER: -1
    VINDICATOR: -1
    WANDERING_TRADER: -1
    WARDEN: -1
    WIND_CHARGE: 200
    WITCH: -1
    WITHER: -1
    WITHER_SKELETON: -1
    WITHER_SKULL: 200
    WOLF: -1
    ZOGLIN: -1
    ZOMBIE: -1
    ZOMBIE_HORSE: -1
    ZOMBIE_VILLAGER: -1
    ZOMBIFIED_PIGLIN: -1
    FISHING_BOBBER: -1
  enable-cached-minecraft-to-bukkit-entitytype-convert: true
  dab:
    enabled: true
    dont-enable-if-in-water: true
    start-distance: 12
    max-tick-freq: 20
    activation-dist-mod: 7
    blacklisted-entities: []
  dont-save-entity:
    dont-save-primed-tnt: false
    dont-save-falling-block: false

###########
#  FIXES  #
###########
fixes:
  dont-place-player-if-server-full: false

##############
#  GAMEPLAY  #
##############
gameplay-mechanisms:
  use-spigot-item-merging-mechanism: true
  # **Experimental feature, report any bugs you encounter!**
  smooth-teleport: false
  # Don't touch this unless you know what you are doing!
  max-item-stack-count:
    max-dropped-items-stack-count: 0
    max-container-destroy-count: 0
  knockback:
    snowball-knockback-players: false
    egg-knockback-players: false
    can-player-knockback-zombie: true
  player:
    disable-moved-wrongly-threshold: false
    max-use-item-distance: 1.0000001

#############
#  NETWORK  #
#############
network:
  protocol-support:
    jade-protocol: false
    appleskin-protocol: true
    asteorbar-protocol: false
    chatimage-protocol: false
    xaero-map-protocol: true
    xaero-map-server-id: 513317
    syncmatica-protocol: false
    syncmatica-quota: false
    syncmatica-quota-limit: 40000000
  chat-message-signature: true

##########
#  MISC  #
##########
misc:
  message:
    unknown-command: <red><lang:command.unknown.command><newline><detail>
  rebrand:
    server-mod-name: Leaf
    server-gui-name: Leaf Console
  sentry:
    # Obtain DSN key from https://sentry.io/
    dsn: ""
    log-level: WARN
    only-log-thrown: true
  secure-seed:
    enabled: false
  remove-vanilla-username-check: true
  remove-spigot-check-bungee-config: true
  remove-change-non-editable-sign-warning: false
  region-format-settings:
    region-format: MCA
    linear-compress-level: 1
    throw-on-unknown-extension-detected: false
    flush-interval-seconds: 5
  lag-compensation:
    enabled: false
    enable-for-water: false
    enable-for-lava: false
  including-5s-in-get-tps: true
  # NOTICE: You must know what you're filling in and how it works! It handles all item stacks!
  hidden-item-components: []
  connection-message:
    join:
      enabled: true
      message: default
    quit:
      enabled: true
      message: default
  cache:
    cache-player-profile-result: true
    cache-player-profile-result-timeout: 1440
